#!/bin/bash

#COMMANDS
# ./toolkit build
clear
echo "Starting toolkit..."

# ./toolkit build
if [ "$1" = "build" ]; then
  if [ ! -d ./dist/zips ]; then
    echo "Generating ZIP's folder..."
    mkdir -p ./dist/zips
    echo "Done!"
  fi
  echo "Starting build..."
  eval cd ./src/template
  eval ls -1 | sed -e 's/\.html$//'
  read -p "What template would you like to build i.e index, email-title-1? " template
  eval cd ../../
  eval mkdir "$template"
  eval cp ./dist/"$template".html ./"$template"/index.html
  eval cp -r ./dist/images ./"$template"
  eval zip -r "$template"-$(date +"%Y-%m-%d").zip ./"$template"
  eval mv -i "$template"-$(date +"%Y-%m-%d").zip dist/zips
  eval rm -rf ./"$template"
  echo "Build created $(date +"%Y-%m-%d");"
else
  echo "Stop saying that Withnail, of course he's the fucking farmer!"
fi
